/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/': RouteRecordInfo<'/admin/dashboard/', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/export/': RouteRecordInfo<'/admin/export/', '/admin/export', Record<never, never>, Record<never, never>>,
    '/admin/settings/': RouteRecordInfo<'/admin/settings/', '/admin/settings', Record<never, never>, Record<never, never>>,
    '/admin/userManage/': RouteRecordInfo<'/admin/userManage/', '/admin/userManage', Record<never, never>, Record<never, never>>,
    '/admin/warnings/': RouteRecordInfo<'/admin/warnings/', '/admin/warnings', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/Register/': RouteRecordInfo<'/auth/Register/', '/auth/Register', Record<never, never>, Record<never, never>>,
    '/detection/': RouteRecordInfo<'/detection/', '/detection', Record<never, never>, Record<never, never>>,
    '/history/': RouteRecordInfo<'/history/', '/history', Record<never, never>, Record<never, never>>,
    '/statistics/': RouteRecordInfo<'/statistics/', '/statistics', Record<never, never>, Record<never, never>>,
    '/templates/': RouteRecordInfo<'/templates/', '/templates', Record<never, never>, Record<never, never>>,
    '/templates/analytics': RouteRecordInfo<'/templates/analytics', '/templates/analytics', Record<never, never>, Record<never, never>>,
    '/templates/knowledge': RouteRecordInfo<'/templates/knowledge', '/templates/knowledge', Record<never, never>, Record<never, never>>,
    '/templates/stats': RouteRecordInfo<'/templates/stats', '/templates/stats', Record<never, never>, Record<never, never>>,
    '/templates/websocket': RouteRecordInfo<'/templates/websocket', '/templates/websocket', Record<never, never>, Record<never, never>>,
    '/userInfo/': RouteRecordInfo<'/userInfo/', '/userInfo', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/dashboard/index.vue': {
      routes: '/admin/dashboard/'
      views: never
    }
    'src/pages/admin/export/index.vue': {
      routes: '/admin/export/'
      views: never
    }
    'src/pages/admin/settings/index.vue': {
      routes: '/admin/settings/'
      views: never
    }
    'src/pages/admin/userManage/index.vue': {
      routes: '/admin/userManage/'
      views: never
    }
    'src/pages/admin/warnings/index.vue': {
      routes: '/admin/warnings/'
      views: never
    }
    'src/pages/auth/login/index.vue': {
      routes: '/auth/login/'
      views: never
    }
    'src/pages/auth/Register/index.vue': {
      routes: '/auth/Register/'
      views: never
    }
    'src/pages/detection/index.vue': {
      routes: '/detection/'
      views: never
    }
    'src/pages/history/index.vue': {
      routes: '/history/'
      views: never
    }
    'src/pages/statistics/index.vue': {
      routes: '/statistics/'
      views: never
    }
    'src/pages/templates/index.vue': {
      routes: '/templates/'
      views: never
    }
    'src/pages/templates/analytics.vue': {
      routes: '/templates/analytics'
      views: never
    }
    'src/pages/templates/knowledge.vue': {
      routes: '/templates/knowledge'
      views: never
    }
    'src/pages/templates/stats.vue': {
      routes: '/templates/stats'
      views: never
    }
    'src/pages/templates/websocket.vue': {
      routes: '/templates/websocket'
      views: never
    }
    'src/pages/userInfo/index.vue': {
      routes: '/userInfo/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
